/* ============================================
   GreenSage — Learn / MasterTeach Content
   Educational articles on sustainability
   ============================================ */

class LearnContent {
  constructor() {
    this.articles = [
      {
        id: 'solar-101',
        icon: '☀️',
        title: 'Solar Energy 101: How Solar Panels Work',
        desc: 'Understand photovoltaic technology, net metering, and why solar is now cheaper than fossil fuels.',
        readTime: '5 min',
        category: 'Energy',
        content: `
          <h3>How Solar Panels Convert Sunlight to Electricity</h3>
          <p>Solar panels use photovoltaic (PV) cells made primarily of silicon. When photons from sunlight hit these cells, they knock electrons loose from atoms, creating an electrical current. This is called the photovoltaic effect, first discovered by Edmond Becquerel in 1839.</p>

          <h3>The Components of a Solar System</h3>
          <ul>
            <li><strong>Solar Panels:</strong> Convert sunlight to DC electricity</li>
            <li><strong>Inverter:</strong> Converts DC to AC electricity for your home</li>
            <li><strong>Meter:</strong> Tracks electricity produced and consumed</li>
            <li><strong>Grid Connection:</strong> Sells excess power back to utility (net metering)</li>
            <li><strong>Battery (optional):</strong> Stores energy for nighttime or outages</li>
          </ul>

          <h3>Why Solar is Now the Cheapest Energy Source</h3>
          <p>The cost of solar has dropped 89% since 2010. In 2024, the average cost is $2.75/watt installed (before tax credits). With the 30% federal Investment Tax Credit (ITC), a typical 8kW system costs around $15,400 after credits.</p>

          <h3>Net Metering: Your Electric Meter Runs Backward</h3>
          <p>When your solar panels produce more electricity than you use, the excess flows back to the grid and your utility gives you credit. This is net metering, and it effectively makes the grid your battery — you export during the day and draw at night.</p>

          <h3>Key Numbers to Know</h3>
          <ul>
            <li>1 kW of solar produces ~1,200-1,600 kWh/year (depending on location)</li>
            <li>Average US home needs 8-10 kW system</li>
            <li>Panels last 25-30+ years with ~0.5% annual degradation</li>
            <li>Payback period: 5-10 years depending on electricity rates and sun</li>
            <li>25-year savings: $20,000-$50,000+</li>
          </ul>
        `
      },
      {
        id: 'carbon-footprint',
        icon: '🌍',
        title: 'Understanding Your Carbon Footprint',
        desc: 'What is a carbon footprint? Where do emissions come from? How can you reduce yours effectively?',
        readTime: '6 min',
        category: 'Climate',
        content: `
          <h3>What Is a Carbon Footprint?</h3>
          <p>Your carbon footprint is the total amount of greenhouse gases (primarily CO₂) generated by your actions. It's measured in tons of CO₂ equivalent per year. The average American produces about 16 tons/year — one of the highest in the world.</p>

          <h3>Where Do Personal Emissions Come From?</h3>
          <ul>
            <li><strong>Transportation (29%):</strong> Cars, trucks, and planes are the #1 source</li>
            <li><strong>Electricity (25%):</strong> Powering homes and buildings</li>
            <li><strong>Industry (23%):</strong> Manufacturing goods we buy</li>
            <li><strong>Food (10-13%):</strong> Agriculture, especially meat production</li>
          </ul>

          <h3>The Power of Individual Action</h3>
          <p>While systemic change is essential, individual actions matter. Research shows that household actions could reduce US emissions by 7.4 gigatons over 10 years (Dietz et al., 2009). The key is focusing on high-impact changes.</p>

          <h3>Top 5 Highest-Impact Personal Actions</h3>
          <ul>
            <li><strong>Go car-free or switch to EV:</strong> Saves 2.4 tons CO₂/year</li>
            <li><strong>Switch to green electricity:</strong> Saves 1.5 tons CO₂/year</li>
            <li><strong>Reduce air travel:</strong> Saves 1.6 tons per round-trip transatlantic flight</li>
            <li><strong>Plant-based diet:</strong> Saves 0.8-1.5 tons CO₂/year</li>
            <li><strong>Insulate your home:</strong> Saves 0.5-1.0 tons CO₂/year</li>
          </ul>

          <h3>The 4-Ton Target</h3>
          <p>To limit global warming to 1.5°C (Paris Agreement), the global average needs to drop to about 2-4 tons per person by 2050. That's a 75% reduction from the current US average. It's ambitious but achievable with today's technology.</p>
        `
      },
      {
        id: 'wind-energy',
        icon: '💨',
        title: 'Wind Energy: The Power of Moving Air',
        desc: 'How wind turbines work, offshore vs onshore, and why wind is the fastest-growing energy source.',
        readTime: '5 min',
        category: 'Energy',
        content: `
          <h3>How Wind Turbines Generate Electricity</h3>
          <p>Wind turbines convert kinetic energy from moving air into electricity. The wind turns large blades connected to a rotor, which spins a generator. Modern turbines can be 850+ feet tall with blades spanning 350+ feet.</p>

          <h3>Onshore vs Offshore Wind</h3>
          <ul>
            <li><strong>Onshore:</strong> Built on land, cheaper to install, most common. Wind speeds 6-9 m/s.</li>
            <li><strong>Offshore:</strong> Built at sea, stronger/steadier winds, more expensive. Wind speeds 8-12+ m/s.</li>
          </ul>

          <h3>Wind Energy Facts</h3>
          <ul>
            <li>Wind provided 10.2% of US electricity in 2023</li>
            <li>A single modern turbine can power 1,500+ homes</li>
            <li>Wind energy has zero water consumption (unlike coal or nuclear)</li>
            <li>Turbines operate 70-80% of the time (capacity factor ~35%)</li>
            <li>Land between turbines can still be farmed</li>
          </ul>

          <h3>Can You Get Wind Power at Home?</h3>
          <p>Small residential wind turbines exist but require consistent wind speeds of 9+ mph. For most homeowners, community solar or green energy plans from your utility are more practical. Check if your utility offers 100% renewable plans.</p>
        `
      },
      {
        id: 'zero-waste',
        icon: '♻️',
        title: 'Zero Waste Living: A Practical Guide',
        desc: 'The 5 Rs, easy swaps, and how to reduce your household waste by 80% without sacrificing convenience.',
        readTime: '7 min',
        category: 'Lifestyle',
        content: `
          <h3>The 5 Rs of Zero Waste (In Order)</h3>
          <ul>
            <li><strong>Refuse:</strong> Say no to what you don't need (straws, receipts, free swag)</li>
            <li><strong>Reduce:</strong> Buy less, choose quality over quantity</li>
            <li><strong>Reuse:</strong> Use what you have, buy secondhand, repair</li>
            <li><strong>Recycle:</strong> Only after refusing, reducing, and reusing</li>
            <li><strong>Rot:</strong> Compost everything organic</li>
          </ul>

          <h3>Easy First Swaps</h3>
          <ul>
            <li>Reusable bags → saves 500+ bags/year</li>
            <li>Reusable water bottle → saves 167+ bottles/year</li>
            <li>Bamboo toothbrush → saves 4 plastic brushes/year</li>
            <li>Bar soap/shampoo → eliminates 6+ plastic bottles/year</li>
            <li>Cloth napkins → saves 2,200+ paper napkins/year</li>
          </ul>

          <h3>The Kitchen (Biggest Impact Area)</h3>
          <p>The kitchen produces the most household waste. Key strategies:</p>
          <ul>
            <li>Buy in bulk with reusable containers</li>
            <li>Use beeswax wraps instead of plastic wrap</li>
            <li>Compost food scraps (30% of landfill waste is food)</li>
            <li>Meal plan to reduce food waste</li>
            <li>Choose products with minimal packaging</li>
          </ul>

          <h3>It's Not About Perfection</h3>
          <p>Zero waste isn't about fitting your trash in a mason jar. It's about making conscious choices. If 100 million people made imperfect zero-waste choices, the impact would be far greater than 100 people being perfectly zero-waste.</p>
        `
      },
      {
        id: 'ev-guide',
        icon: '🚗',
        title: 'Electric Vehicles: The Complete Guide',
        desc: 'EV types, charging, range anxiety, costs, and why EVs are cheaper to own than gas cars.',
        readTime: '6 min',
        category: 'Transport',
        content: `
          <h3>Types of Electric Vehicles</h3>
          <ul>
            <li><strong>BEV (Battery Electric):</strong> 100% electric, no gas engine. Tesla, Rivian, Chevy Bolt.</li>
            <li><strong>PHEV (Plug-in Hybrid):</strong> Battery + small gas engine. 20-50 mile electric range.</li>
            <li><strong>HEV (Hybrid):</strong> Gas engine + small battery. Can't plug in. Toyota Prius.</li>
          </ul>

          <h3>Total Cost of Ownership</h3>
          <p>EVs are cheaper to own over time despite higher purchase prices:</p>
          <ul>
            <li><strong>Fuel:</strong> ~$0.04/mile (electric) vs ~$0.12/mile (gas) — 70% savings</li>
            <li><strong>Maintenance:</strong> No oil changes, fewer brake replacements (regen braking). ~40% less maintenance.</li>
            <li><strong>Tax Credits:</strong> Up to $7,500 federal + state credits</li>
            <li><strong>5-year savings:</strong> $6,000-$12,000 vs comparable gas car</li>
          </ul>

          <h3>Charging: Easier Than You Think</h3>
          <ul>
            <li><strong>Level 1 (120V):</strong> Regular outlet, ~4 miles/hour. Good for overnight.</li>
            <li><strong>Level 2 (240V):</strong> Home charger, ~25-30 miles/hour. Full charge overnight.</li>
            <li><strong>DC Fast Charge:</strong> Public stations, 200+ miles in 30 min.</li>
          </ul>

          <h3>Range Anxiety is Overblown</h3>
          <p>The average American drives 37 miles/day. Most modern EVs have 250-350+ mile range. 80% of charging happens at home. For road trips, DC fast chargers are increasingly available along major highways.</p>

          <h3>Environmental Impact</h3>
          <p>Even with grid electricity, EVs produce 50-70% fewer emissions than gas cars over their lifetime. As the grid gets cleaner, EVs get cleaner automatically.</p>
        `
      },
      {
        id: 'water-conservation',
        icon: '💧',
        title: 'Water Conservation: Every Drop Counts',
        desc: 'Simple strategies to cut water usage by 30-50% and protect this precious resource.',
        readTime: '5 min',
        category: 'Water',
        content: `
          <h3>Why Water Conservation Matters</h3>
          <p>Only 1% of Earth's water is accessible freshwater. Climate change is making droughts more frequent and severe. The average American uses 82 gallons per day — much of it wasted.</p>

          <h3>Where Water Goes in Your Home</h3>
          <ul>
            <li>Toilet: 24%</li>
            <li>Shower: 20%</li>
            <li>Faucets: 19%</li>
            <li>Washing machine: 17%</li>
            <li>Leaks: 12%</li>
            <li>Other: 8%</li>
          </ul>

          <h3>High-Impact Water Savings</h3>
          <ul>
            <li><strong>Fix leaks:</strong> A dripping faucet wastes 3,000 gal/year</li>
            <li><strong>Low-flow showerhead:</strong> Saves 2,700 gal/year</li>
            <li><strong>Dual-flush toilet:</strong> Saves 4,000 gal/year</li>
            <li><strong>Shorter showers:</strong> Saves 2 gal/minute</li>
            <li><strong>Full loads only:</strong> Saves 15-45 gal/load</li>
            <li><strong>Rainwater harvesting:</strong> Free water for gardens</li>
          </ul>

          <h3>The Water-Energy Connection</h3>
          <p>Heating water accounts for 18% of home energy use. Saving hot water saves energy too. A low-flow showerhead saves both water AND ~330 kWh/year in water heating.</p>
        `
      },
      {
        id: 'sustainable-food',
        icon: '🥗',
        title: 'Sustainable Eating: Food for the Planet',
        desc: 'How your food choices impact the climate, and delicious ways to eat more sustainably.',
        readTime: '5 min',
        category: 'Food',
        content: `
          <h3>Food's Climate Impact</h3>
          <p>The food system is responsible for 26% of global greenhouse gas emissions. But not all foods are created equal — the difference between the highest and lowest impact foods is 50x.</p>

          <h3>Carbon Footprint by Food Type (kg CO₂ per kg of food)</h3>
          <ul>
            <li>Beef: 27 kg CO₂ per kg</li>
            <li>Lamb: 24 kg CO₂ per kg</li>
            <li>Cheese: 13.5 kg CO₂ per kg</li>
            <li>Pork: 7 kg CO₂ per kg</li>
            <li>Chicken: 6.9 kg CO₂ per kg</li>
            <li>Fish: 5 kg CO₂ per kg</li>
            <li>Eggs: 4.8 kg CO₂ per kg</li>
            <li>Rice: 2.7 kg CO₂ per kg</li>
            <li>Tofu: 2 kg CO₂ per kg</li>
            <li>Vegetables: 0.5 kg CO₂ per kg</li>
            <li>Fruits: 0.4 kg CO₂ per kg</li>
          </ul>

          <h3>You Don't Have to Go Vegan</h3>
          <p>Simply reducing beef and lamb consumption has the biggest impact. Replacing beef with chicken reduces emissions by 75%. Replacing it with beans or lentils reduces it by 90%. Even one meatless day per week makes a meaningful difference.</p>

          <h3>Reduce Food Waste</h3>
          <p>30-40% of food in the US is wasted. That's $1,500/year per household thrown away. Plan meals, use leftovers creatively, freeze extras, and compost what you can't eat.</p>
        `
      },
      {
        id: 'green-home',
        icon: '🏠',
        title: 'Green Home: Energy-Efficient Living',
        desc: 'Practical upgrades to make your home more efficient and comfortable while saving money.',
        readTime: '6 min',
        category: 'Home',
        content: `
          <h3>The Biggest Energy Wasters in Your Home</h3>
          <ul>
            <li><strong>Heating/Cooling (46%):</strong> The single biggest energy expense</li>
            <li><strong>Water Heating (14%):</strong> Second largest energy use</li>
            <li><strong>Appliances (13%):</strong> Refrigerator, washer, dryer</li>
            <li><strong>Lighting (9%):</strong> Easy wins with LED upgrades</li>
            <li><strong>Electronics (6%):</strong> Phantom loads add up</li>
          </ul>

          <h3>Quick Wins (Under $100)</h3>
          <ul>
            <li>LED bulb swap — $2-5/bulb, saves $75/yr per bulb</li>
            <li>Smart power strips — $25-40, saves $100/yr</li>
            <li>Weather stripping doors — $10-20, saves 5-10% heating</li>
            <li>Programmable thermostat — $25-50, saves 10%</li>
            <li>Low-flow showerheads — $15-30, saves water + energy</li>
          </ul>

          <h3>Medium Investments ($100-$1,000)</h3>
          <ul>
            <li>Attic insulation — $500-1,500, saves 15-20% on heating</li>
            <li>Smart thermostat — $150-250, saves 10-15%</li>
            <li>Energy Star appliances — when replacing, always choose Energy Star</li>
            <li>Window film/treatments — $100-300, reduces cooling costs</li>
          </ul>

          <h3>Major Upgrades ($1,000+)</h3>
          <ul>
            <li>Solar panels — $15,000-25,000, payback in 5-10 years</li>
            <li>Heat pump — $4,000-8,000, 2-3x more efficient than furnace</li>
            <li>Energy-efficient windows — $300-700/window, 15% energy savings</li>
            <li>Home battery — $10,000-15,000, energy independence</li>
          </ul>
        `
      }
    ];
  }

  getArticles() {
    return this.articles.map(a => ({
      id: a.id,
      icon: a.icon,
      title: a.title,
      desc: a.desc,
      readTime: a.readTime,
      category: a.category
    }));
  }

  getArticle(id) {
    return this.articles.find(a => a.id === id);
  }
}

window.learnContent = new LearnContent();
